app:
  name: go1
  port: 8080
  env: development

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: go1_db
  max_conns: 20
  min_conns: 5

redis:
  addr: localhost:6379

kafka:
  brokers: localhost:9099
  groupId: user-worker-group
  retry:
    retrySuffix: ".retry"
    dlqSuffix: ".dlq"
    topics:
      user_created:
        enableRetry: true
        maxAttempts: 3
        backoffMs: 2000
      # Example: topic without retry
      # order_created:
      #   enableRetry: false

jaeger:
  endpoint: localhost:4318
